DROP TABLE IF EXISTS USER;
CREATE TABLE `USER` (
    `ID` BIGINT NOT NULL COMMENT '主键',
    `CREATED` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
    `CREATED_BY` BIGINT DEFAULT '0' COMMENT '创建人',
    `UPDATED` TIMESTAMP NULL DEFAULT NULL COMMENT '更新时间',
    `UPDATED_BY` BIGINT DEFAULT '0' COMMENT '更新人',
    `IS_ACTIVE` CHAR(1) DEFAULT 'Y' COMMENT '是否激活',
    `IS_DELETED` CHAR(1) DEFAULT 'N' COMMENT '是否已删除',
	`GROUP_ID` VARCHAR(64) DEFAULT '0' COMMENT '组ID',
    `NAME` VARCHAR(64) DEFAULT NULL COMMENT '姓名',
    `EMAIL` VARCHAR(64) DEFAULT NULL COMMENT '邮件',
    `PASSWORD` VARCHAR(64) DEFAULT NULL COMMENT '密码',
    `ACCOUNT` VARCHAR(64) COMMENT '账号',
    PRIMARY KEY (`ID`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='用户信息';

DROP TABLE IF EXISTS `ACCESS`;
CREATE TABLE IF NOT EXISTS `ACCESS` (
    `ID` BIGINT NOT NULL COMMENT '主键',
    `CREATED` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
    `CREATED_BY` BIGINT DEFAULT '0' COMMENT '创建人',
    `UPDATED` TIMESTAMP NULL DEFAULT NULL COMMENT '更新时间',
    `UPDATED_BY` BIGINT DEFAULT '0' COMMENT '更新人',
    `IS_ACTIVE` CHAR(1) DEFAULT 'Y' COMMENT '是否激活',
    `IS_DELETED` CHAR(1) DEFAULT 'N' COMMENT '是否已删除',
	`GROUP_ID` VARCHAR(64) DEFAULT '0' COMMENT '组ID',
    `ROLE_ID` BIGINT NOT NULL COMMENT '角色ID',
    `NODE_ID` BIGINT NOT NULL COMMENT '节点ID',
    `LEVEL` TINYINT(1) NOT NULL COMMENT '级别',
    `MODULE` VARCHAR(64) DEFAULT NULL COMMENT '模块名',
    KEY `ROLE_ID` (`ROLE_ID`),
    KEY `NODE_ID` (`NODE_ID`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='访问控制';
 
DROP TABLE IF EXISTS `NODE`;
CREATE TABLE IF NOT EXISTS `NODE` (
    `ID` BIGINT NOT NULL COMMENT '主键',
    `CREATED` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
    `CREATED_BY` BIGINT DEFAULT '0' COMMENT '创建人',
    `UPDATED` TIMESTAMP NULL DEFAULT NULL COMMENT '更新时间',
    `UPDATED_BY` BIGINT DEFAULT '0' COMMENT '更新人',
    `IS_ACTIVE` CHAR(1) DEFAULT 'Y' COMMENT '是否激活',
    `IS_DELETED` CHAR(1) DEFAULT 'N' COMMENT '是否已删除',
	`GROUP_ID` VARCHAR(64) DEFAULT '0' COMMENT '组ID',
    `NAME` VARCHAR(64) NOT NULL COMMENT '名称',
    `TITLE` VARCHAR(64) DEFAULT NULL COMMENT '标题',
    `REMARK` VARCHAR(256) DEFAULT NULL COMMENT '备注',
    `SORT` BIGINT DEFAULT NULL COMMENT '排序',
    `PID` BIGINT NOT NULL COMMENT '父节点ID',
    `LEVEL` TINYINT(1) NOT NULL COMMENT '级别',
    PRIMARY KEY (`ID`),
    KEY `LEVEL` (`LEVEL`),
    KEY `PID` (`PID`),
    KEY `NAME` (`NAME`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='节点';

DROP TABLE IF EXISTS `ROLE`;
CREATE TABLE IF NOT EXISTS `ROLE` (
    `ID` BIGINT NOT NULL COMMENT '主键',
    `CREATED` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
    `CREATED_BY` BIGINT DEFAULT '0' COMMENT '创建人',
    `UPDATED` TIMESTAMP NULL DEFAULT NULL COMMENT '更新时间',
    `UPDATED_BY` BIGINT DEFAULT '0' COMMENT '更新人',
    `IS_ACTIVE` CHAR(1) DEFAULT 'Y' COMMENT '是否激活',
    `IS_DELETED` CHAR(1) DEFAULT 'N' COMMENT '是否已删除',
	`GROUP_ID` VARCHAR(64) DEFAULT '0' COMMENT '组ID',
    `NAME` VARCHAR(64) NOT NULL COMMENT '角色名',
    `PID` BIGINT DEFAULT NULL COMMENT '父角色ID',
    `REMARK` VARCHAR(256) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`ID`),
    KEY `PID` (`PID`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='角色';

DROP TABLE IF EXISTS `ROLE_USER`;
CREATE TABLE IF NOT EXISTS `ROLE_USER` (
    `ID` BIGINT NOT NULL COMMENT '主键',
    `CREATED` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
    `CREATED_BY` BIGINT DEFAULT '0' COMMENT '创建人',
    `UPDATED` TIMESTAMP NULL DEFAULT NULL COMMENT '更新时间',
    `UPDATED_BY` BIGINT DEFAULT '0' COMMENT '更新人',
    `IS_ACTIVE` CHAR(1) DEFAULT 'Y' COMMENT '是否激活',
    `IS_DELETED` CHAR(1) DEFAULT 'N' COMMENT '是否已删除',
	`GROUP_ID` VARCHAR(64) DEFAULT '0' COMMENT '组ID',
    `ROLE_ID` BIGINT DEFAULT NULL COMMENT '角色ID',
    `USER_ID` BIGINT DEFAULT NULL COMMENT '用户ID',
    KEY `GROUP_ID` (`ROLE_ID`),
    KEY `USER_ID` (`USER_ID`)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='用户角色关系';